# Generated by Django 2.0.6 on 2018-06-25 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mem', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='muse',
            old_name='use',
            new_name='muse',
        ),
    ]
